### ISSUE TITLE
Hot to fully uninstall this?

### ISSUE THREAD

**Issue by ibin7777** [blackswanlab/windows-10-folder-icon-changer#1]
I couldn't find a way to remove the context menu.

**Comment by amirhp-com** [comment]
Hello,
1. Remove file from C:\Windows\wtfic.exe
2. Run regedit.exe, then delete **Computer\HKEY_CLASSES_ROOT\Folder\shell\wtfic**

**Comment by ibin7777** [comment]
Thanks!
